events {}
http {
    client_max_body_size 10G; 
    server {
        listen 80;
        server_name somethings.poorthings.moi;

        location / {
            proxy_pass http://somethings:5487; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /storage/ {
            proxy_pass http://somethings:9379/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
